.PHONY: start stop restart logs reload status upload upload-local play install-pack pack ping
.PHONY: maze sphere cube pyramid test
.PHONY: build build-cube build-sphere build-pyramid build-maze build-test test-command

# Docker commands
start:
	docker compose up -d

stop:
	docker compose down

restart:
	docker compose restart

logs:
	docker compose logs -f

reload:
	docker exec minecraft-bedrock send-command "reload"

status:
	docker compose ps

play:
	powershell.exe -Command "Start-Process 'minecraft://connect/?serverUrl=127.0.0.1&serverPort=19133'"

# Structure generators - write chunks to file
# Usage: make maze [WIDTH=15] [HEIGHT=7] [LENGTH=15] [BLOCK=minecraft:stone_bricks]
maze:
	@node tools/generators/maze.cjs $(or $(WIDTH),15) $(or $(HEIGHT),7) $(or $(LENGTH),15) $(or $(BLOCK),minecraft:stone_bricks) > structure.chunks

# Usage: make sphere [RADIUS=5] [BLOCK=minecraft:glass] [HOLLOW=true]
sphere:
	@node tools/generators/sphere.cjs $(or $(RADIUS),5) $(or $(BLOCK),minecraft:glass) $(or $(HOLLOW),true) > structure.chunks

# Usage: make cube [SIZE=10] [BLOCK=minecraft:stone] [HOLLOW=true]
cube:
	@node tools/generators/cube.cjs $(or $(SIZE),10) $(or $(BLOCK),minecraft:stone) $(or $(HOLLOW),true) > structure.chunks

# Usage: make pyramid [BASE=15] [BLOCK=minecraft:sandstone]
pyramid:
	@node tools/generators/pyramid.cjs $(or $(BASE),15) $(or $(BLOCK),minecraft:sandstone) > structure.chunks

# Usage: make test [PATTERN=frame] [SIZE=10]
# Patterns: checkerboard, stripes, frame, cross, corner, small, line
test:
	@node tools/generators/test.cjs $(or $(PATTERN),frame) $(or $(SIZE),10) > structure.chunks

# Ping Realm to test connection (stays connected 30s, sends test command)
ping: tools/upload-realm/upload-realm
	tools/upload-realm/upload-realm -ping

# Upload chunks to Realm via gophertunnel (set REALM_INVITE or create .realm-invite)
upload: tools/upload-realm/upload-realm
	tools/upload-realm/upload-realm -chunks structure.chunks

# Build structure on Realm by placing blocks directly (creative mode)
# Usage: make build (uses structure.blocks generated by build-* targets)
build: tools/upload-realm/upload-realm
	tools/upload-realm/upload-realm -build -blocks structure.blocks

# Generate block files and build on Realm (one-step targets)
# Usage: make build-cube [SIZE=3] [BLOCK=minecraft:stone] [HOLLOW=true]
build-cube: tools/upload-realm/upload-realm
	@node tools/generators/cube.cjs $(or $(SIZE),3) $(or $(BLOCK),minecraft:stone) $(or $(HOLLOW),true) --blocks > structure.blocks
	tools/upload-realm/upload-realm -build -blocks structure.blocks

# Usage: make build-sphere [RADIUS=3] [BLOCK=minecraft:glass] [HOLLOW=true]
build-sphere: tools/upload-realm/upload-realm
	@node tools/generators/sphere.cjs $(or $(RADIUS),3) $(or $(BLOCK),minecraft:glass) $(or $(HOLLOW),true) --blocks > structure.blocks
	tools/upload-realm/upload-realm -build -blocks structure.blocks

# Usage: make build-pyramid [BASE=7] [BLOCK=minecraft:sandstone]
build-pyramid: tools/upload-realm/upload-realm
	@node tools/generators/pyramid.cjs $(or $(BASE),7) $(or $(BLOCK),minecraft:sandstone) --blocks > structure.blocks
	tools/upload-realm/upload-realm -build -blocks structure.blocks

# Usage: make build-maze [WIDTH=11] [HEIGHT=5] [LENGTH=11] [BLOCK=minecraft:stone_bricks]
build-maze: tools/upload-realm/upload-realm
	@node tools/generators/maze.cjs $(or $(WIDTH),11) $(or $(HEIGHT),5) $(or $(LENGTH),11) $(or $(BLOCK),minecraft:stone_bricks) --blocks > structure.blocks
	tools/upload-realm/upload-realm -build -blocks structure.blocks

# Usage: make build-test [PATTERN=small] [SIZE=10]
build-test: tools/upload-realm/upload-realm
	@node tools/generators/test.cjs $(or $(PATTERN),small) $(or $(SIZE),10) --blocks > structure.blocks
	tools/upload-realm/upload-realm -build -blocks structure.blocks

# Track A: Test if bedrock-protocol npm can send commands to Realm
test-command:
	node tools/upload-realm/test-command.cjs

# Install behavior pack to Realm (one-time setup)
install-pack: tools/upload-realm/upload-realm
	tools/upload-realm/upload-realm -install-pack

tools/upload-realm/upload-realm: tools/upload-realm/*.go
	cd tools/upload-realm && go build -o upload-realm .

# Upload chunks to local Docker server
upload-local:
	@while read chunk; do \
		docker exec minecraft-bedrock send-command "scriptevent burnodd:chunk $$chunk"; \
	done < structure.chunks

# Build .mcpack file for import into Minecraft
# Output: output/burnodd_scripts.mcpack (double-click to import)
pack: tools/pack-builder/pack-builder
	tools/pack-builder/pack-builder

tools/pack-builder/pack-builder: tools/pack-builder/*.go
	cd tools/pack-builder && go build -o pack-builder .
